### ISSUE TITLE
Fixed problem with graal or use jlink

### ISSUE THREAD

**Issue by robertmakrytski** [gdevby/desktop-starter-launch-update-bootstrap#25]
https://github.com/oracle/graal/issues?q=is%3Aissue+LogFactoryImpl+is%3Aclosed
There is advice concept
[google link](https://www.google.com/search?q=graalmv+class+not+found+LogFactoryImpl&sca_esv=579484062&sxsrf=AM9HkKmG8YidwNbOcZJsLn8CssYZ_jxJGg%3A1699121842267&ei=sopGZaTyD8LawPAP-_G7-AE&ved=0ahUKEwikk9qO-qqCAxVCLRAIHfv4Dh8Q4dUDCBA&uact=5&oq=graalmv+class+not+found+LogFactoryImpl&gs_lp=Egxnd3Mtd2l6LXNlcnAiJmdyYWFsbXYgY2xhc3Mgbm90IGZvdW5kIExvZ0ZhY3RvcnlJbXBsMgYQABgeGA0yCBAAGAgYHhgNSJxNUOE9WLNMcBF4AJABAJgBR6ABR6oBATG4AQPIAQD4AQH4AQLCAgoQABhHGNYEGLADwgIHECMYsAIYJ8ICBxAAGA0YgATCAggQABgeGA0YCsICCRAAGA0YExiABMICCBAAGB4YDRgTwgIKEAAYCBgeGA0YE8ICCBAAGBYYHhgTwgIGEAAYFhge4gMEGAAgQYgGAZAGCA&sclient=gws-wiz-serp#ip=1)

**Comment by robertmakrytski** [comment]
https://github.com/oracle/graal/issues/3084 
Not possible use for awt java

**Comment by robertmakrytski** [comment]
We will use jlink which created in java 9.

**Comment by gdevby** [comment]
При замене ссылаться на это, так как проблема с awt  или swing

**Comment by gdevby** [comment]
У нас там есть статья, надо написать в её, что у нас ен вышло , проблема по таким причинам.
